name: Clean Up

on:
  workflow_run:
    workflows: [Process Issues]
    types:
      - completed
      
jobs:
  build:
    name: Remove runs 
    runs-on: ubuntu-latest
    steps:
      - name: Run it
        run: |
          for i in $(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/sensepost-public/can-you-leek-me/actions/runs -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" | grep \"url\" | grep '/actions/runs/' | cut -d ' ' -f 8 | tr -d '"' | tr -d ','); do curl -X DELETE -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" $i; done
          
